import React from 'react';
import { motion } from 'framer-motion';
import { useAuth } from '@/contexts/SupabaseAuthContext';
import { Button } from '@/components/ui/button';
import { LogIn, LogOut, Sun, Moon, User, Settings, CloudSun, Cloud } from 'lucide-react';

const Header = ({ onAuthClick, onSettingsClick, theme, toggleTheme, skyEnabled, onToggleSky }) => {
  const { session, signOut } = useAuth();
    const handleLogout = async () => { await signOut(); };
      const userName = session?.user?.email ? session.user.email.split('@')[0] : null;
        return (
            <motion.header initial={{ y: -48, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.45, ease: 'easeOut' }}
                  className="sticky top-0 z-40 border-b border-border/60 bg-background/80 backdrop-blur-md">
                        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 md:px-6 lg:px-8">
                                <div className="flex items-center gap-3 md:gap-4">
                                          <motion.div whileHover={{ scale: 1.05, rotate: 3 }} transition={{ type: 'spring', stiffness: 400, damping: 15 }}
                                                      className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-accent/90 via-accent to-accent/70 shadow-sm">
                                                                  <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F5F1E8]">
                                                                                <img src="https://i.imgur.com/PO0c4Td.png" alt="Freraut Invest" className="h-7 w-7 object-contain" onError={(e) => { e.currentTarget.style.display = 'none'; }} />
                                                                                            </div>
                                                                                                      </motion.div>
                                                                                                                <div className="flex flex-col">
                                                                                                                            <div className="flex items-center gap-2">
                                                                                                                                          <h1 className="text-lg font-semibold tracking-[0.18em] text-accent md:text-xl">FRERAUT INVEST</h1>
                                                                                                                                                        {session && <span className="hidden rounded-full border border-accent/20 bg-accent/5 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-accent md:inline">Dashboard</span>}
                                                                                                                                                                    </div>
                                                                                                                                                                                {session ? (
                                                                                                                                                                                              <p className="mt-0.5 text-xs text-muted-foreground">Sesión iniciada como <span className="font-medium text-foreground">{userName}</span></p>
                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                        <p className="mt-0.5 text-xs text-muted-foreground">Plataforma privada de inversión y análisis.</p>
                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              <div className="flex items-center gap-2 md:gap-3">
                                                                                                                                                                                                                                                                        {theme === 'light' && onToggleSky && (
                                                                                                                                                                                                                                                                                    <motion.button onClick={onToggleSky} whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.95 }}
                                                                                                                                                                                                                                                                                                  className={`inline-flex h-9 w-9 items-center justify-center rounded-full border shadow-sm transition-all ${skyEnabled ? 'border-blue-300 bg-blue-50 text-blue-500' : 'border-border/60 bg-background/60 text-muted-foreground'}`}
                                                                                                                                                                                                                                                                                                                title={skyEnabled ? 'Desactivar cielo animado' : 'Activar cielo animado'}>
                                                                                                                                                                                                                                                                                                                              {skyEnabled ? <CloudSun className="h-4 w-4" /> : <Cloud className="h-4 w-4" />}
                                                                                                                                                                                                                                                                                                                                          </motion.button>
                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                              <button onClick={toggleTheme} className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 bg-background/60 text-muted-foreground shadow-sm transition-all hover:border-accent/60 hover:text-accent" aria-label="Cambiar tema">
                                                                                                                                                                                                                                                                                                                                                                          {theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                              {session ? (
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2 md:gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={onSettingsClick} className="group flex items-center gap-2 rounded-full border border-border/60 bg-background/60 px-3 py-1.5 text-xs text-muted-foreground shadow-sm transition-all hover:border-accent/60 hover:text-accent">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <User className="h-3.5 w-3.5 text-accent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="hidden max-w-[140px] truncate md:inline">{session.user.email}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Settings className="h-3.5 w-3.5 opacity-60" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button onClick={handleLogout} variant="outline" size="sm" className="inline-flex items-center gap-1.5 rounded-full border-accent/60 bg-accent/5 px-3.5 text-xs font-medium text-accent">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <LogOut className="h-3.5 w-3.5" /><span>Salir</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button onClick={onAuthClick} size="sm" className="inline-flex items-center gap-1.5 rounded-full bg-accent px-4 text-xs font-semibold text-background">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <LogIn className="h-3.5 w-3.5" /><span>Entrar / Crear cuenta</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
export default Header;